In [1]:
import numpy as np
a = np.array([[11,2,4,8,7],[2,34,12,45,67],[11,77,55,26,45],[12,23,45,6,21],[10,9,17,16,3]])
print("a =",a)
b = int(input("Enter the row (0 to 4):"))
c = int(input("Enter the column (0 to 4):"))
print("Element: ",a[b,c])

N4=[]
if b+1<5:
    N4.append(a[b+1,c])
if b-1>=0:
    N4.append(a[b-1,c])
if c+1<5:
    N4.append(a[b,c+1])
if c-1>=0:
    N4.append(a[b,c-1])
print("\nNeighbours of N4: ",N4)

Nd = []
    
if b+1<5 and c+1<5:
    Nd.append(a[b+1,c+1])
if b+1<5 and c-1>=0:
    Nd.append(a[b+1,c-1])
if b-1>=0 and c+1<5:
    Nd.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    Nd.append(a[b-1,c-1])
print("\nDiagonal Neighbours Nd: ",Nd)

N8 = []

if b+1<5:
    N8.append(a[b+1,c])
if b-1>=0:
    N8.append(a[b-1,c])
if c+1<5:
    N8.append(a[b,c+1])
if c-1>=0:
    N8.append(a[b,c-1])
if b+1<5 and c+1<5:
    N8.append(a[b+1,c+1])
if b+1<5 and c-1>=0:
    N8.append(a[b+1,c-1])
if b-1>=0 and c+1<5:
    N8.append(a[b-1,c+1])
if b-1>=0 and c-1>=0:
    N8.append(a[b-1,c-1])
print("\nNeighbours of N8: ",N8)

a = [[11  2  4  8  7]
 [ 2 34 12 45 67]
 [11 77 55 26 45]
 [12 23 45  6 21]
 [10  9 17 16  3]]


Enter the row (0 to 4): 2
Enter the column (0 to 4): 2


Element:  55

Neighbours of N4:  [np.int64(45), np.int64(12), np.int64(26), np.int64(77)]

Diagonal Neighbours Nd:  [np.int64(6), np.int64(23), np.int64(45), np.int64(34)]

Neighbours of N8:  [np.int64(45), np.int64(12), np.int64(26), np.int64(77), np.int64(6), np.int64(23), np.int64(45), np.int64(34)]
